### PR TITLE
Firebase, PouchDB/CouchDB, Offline Interceptor

### PR DESCRIPTION
**Pull request by valterkraemer**
Think it's time to add these 😄

### CODE REVIEW

**Comment by LeaVerou** [comment]
Yay!!!

A few minor issues:

- You added Firebase twice
- Ids need to be unique. Maybe `firebase2`? I'm also fine with making this the canonical Firebase backend, if you’re willing to work on it and maintain it. In that case, the other Firebase plugin needs to change id. 
-It would be good to briefly explain what "4 way data binding" is in the description. Remember our target audience is not necessarily a developer, and even many developers don't know what it is (until recently I didn't either. Since I learned what it is, I mentioned it to multiple other devs, I have not found **one** that knows what it is).

**Comment by LeaVerou** [comment]
By "the other Firebase plugin" I wasn't referring to your duplicate, I could tell that was in error. I was referring to (@lizziew’s plugin](https://plugins.mavo.io/plugin/firebase). One of them needs to change id.

**Comment by valterkraemer** [comment]
Sorry about the mess :)

I assumed that it would make some kind of conflict. By I still wanted to make it the primary one when the other one haven't had an update in half a year.

What happened with the other plugin? Earlier you said that the work would continue in Autumn.

**Comment by LeaVerou** [comment]
Just sent an email to @lizziew to see if she prefers some other id over `firebase2`.

> By I still wanted to make it the primary one when the other one haven't had an update in half a year.

Yes you're right in that reasoning and I agree with making this the primary one since at this point it's much more maintained. I’m not sure I like `firebase2` for Lizzie's plugin though given that it came first. I hope we can think of a better name, otherwise perhaps `firebase0`?

> What happened with the other plugin? Earlier you said that the work would continue in Autumn.

That was the plan, but Lizzie took on too much other work and told me she can't work on this until January. :(

**Comment by lizziew** [comment]
Hi Lea and Valter,

Changing my repo’s ID is completely fine with me! :) Anything (firebase0,
firebase2 or firebase_proto) works!

Thank you!
Lizzie

**Comment by LeaVerou** [comment]
@valterkraemer can you change Lizzie's plugin id to firebase0? Promise, this is the last change, then we can merge :)

**Comment by LeaVerou** [comment]
Merged, woohoo!!
Really excited about these. Thank you for working on them!

Btw do you have a twitter account so I @-mention you when I tweet about them?

**Comment by valterkraemer** [comment]
👍 

Yeah, rarely use it but @valterkraemer

**Comment by LeaVerou** [comment]
Done: https://twitter.com/mavoweb/status/927618391132725248 :)

**Pull request merged**
