### PR TITLE
First iteration for the new GitHub PR plugin

### PR DESCRIPTION
**Pull request by DmitrySharabin**
I moved the PR code from the GitHub backend and shaped a code a bit. Nothing fancy.

### CODE REVIEW

**Comment by DmitrySharabin** [comment]
I was also thinking about naming; should we call this plugin `githubpr`? I use an analogy with `jasonld`, `tynimce`, etc.

**Comment by LeaVerou** [comment]
I think github-pr is fine.
I merged this, but I just realized we need to move the phrases too.
Also, could you please add a readme about how this works?
Are you adding the pullRequest method to the plugin, and not the Github backend? Why?
Thank you!

**Comment by DmitrySharabin** [comment]
> Are you adding the pullRequest method to the plugin, and not the Github backend? Why?

Do you mean like this?

```javascript
Mavo.Plugins.register("github-pr", {
  extend: {
    Backend.Github: {
      pullRequest: function (existing) { ... }
    }
  },

  hooks: { ... }
});
```

To be honest, I never knew how to use it correctly. 😅 I believe now is the right time to do that. Will send you another PR when I can manage it.

**Comment by LeaVerou** [comment]
Looking at [the code](https://github.com/mavoweb/mavo/blob/master/src/plugins.js#L59) for the `extend` parameter, it's not gonna work for `Backend.Github`, and we shouldn't be adding a method that only makes sense for the Github Backend onto `Backend`. 
Just do it manually:

`Backend.Github.prototype = function() { ... }`

**Comment by DmitrySharabin** [comment]
Yep! I already checked it. Thanks for the idea. I am almost done with the changes. :)

**Pull request merged**
