### PR TITLE
[github-pr] Fix broken preview URL

### PR DESCRIPTION
**Pull request by DmitrySharabin**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thank you so much Dmitry for working on this. Could you tell me a little bit about how this code change is fixing the issue? I can't quite infer it from the diff.

**Comment by DmitrySharabin** [comment]
Sure, Lea. With pleasure. It might be I won't be very correct in wording (sorry about that in advance) but I'll do my best. 🙈

Before sending a PR, we build the preview URL based on the current location tweaking it a bit if needed (by pointing an app's storage to another repo). And it worked well while the only thing an author specified in their app was `storage`. But what if an author specified `source` as well? In that case, Mavo shows data from the source and stores data in the storage. And since we didn't redefine `source` in the preview URL, a reviewer of a PR couldn't see the suggested changes stored in the _storage_. What they did see was data from the app's _source_. This is exactly the issue we faced with the docs on the Mavo website:

```html
<body mv-app="docs"
      mv-storage="https://github.com/mavoweb/mavo.io/docs/docs.json" mv-source="/docs/docs.json">
```

We modify location in two cases (that's why they share almost the same code): when switching to a fork and after committing to a fork. In both these cases, we modified only `storage` leaving `source` untouched. And I tried to fix that by disabling `source` so that `storage` takes precedence (see lines 150 through 158).

I also noticed that previously we appended search parameters instead of re-setting them. It also could cause some bugs.

And last but not least. I also tried to cover the case when a PR is sent to a repo specified via URL, i.e. when we have either `storage` or `appId-storage` search param. In that case, we don't want to set the `appId-storage` search param that will _not_ override the `storage` param, if the latter was already set. We want to re-set the existing param. That's why I do all these checks in lines 143 through 145 (and in 153 through 155).

And since after all these manipulations we have the correct location pointing to the correct storage (and the source is disabled if needed), there is no need to modify it somehow in the `pullRequest` method, we can use It as it is. That's why I deleted lines 8 through 13.

Hope my explanation makes sense.

**Comment by LeaVerou** [comment]
I'm not sure about modifying a the source when it's actually the storage that uses GitHub, that might be too much magic. In this case it was just an optimization, but it in other cases it may be a completely different source, e.g. for apps that read from one place and write to another place.
Perhaps this is something that needs to be fixed in the docs app (by removing the source), and not in Mavo.
Have we seen this issue in any other app?
@karger what do you think?

> I also noticed that previously we appended search parameters instead of re-setting them. It also could cause some bugs.

That should definitely be fixed regardless.

**Comment by DmitrySharabin** [comment]
There is one thing that still bothers me. When end-users store their data in a fork, we suggest them to switch to the fork only when there is no source. It totally makes sense if the source has priority over the storage. But how would end-users see the data they store in their repo if an author provided not only the storage but also the source? How would they guess that they must disable the source to see their data if we don't do that ourselves? Even though they try to add the `storage` (`appId-storage`) param to the URL, it won't take effect either. They won't see their data.

It might be that the case I describe is an edge case and there is no need to worry about it since it's rather rare?
However, we can still take this case into account only in the `github-pr` plugin when we build the preview URL and don't change the Mavo behavior.

**Comment by DmitrySharabin** [comment]
The corresponding PR in the Mavo repo is closed. So, I'm going to close this one as well.

**Pull request closed without merging**
