### PR TITLE
Added screenshots

### PR DESCRIPTION
**Pull request by DmitrySharabin**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks!

**Comment by DmitrySharabin** [comment]
The screenshots are not shown. 😭
What is the proper way to include screenshots to a plugin README? I always struggle with it: first, I upload them to a repo with the Github Pages enabled, and then I include them using an absolute URL that Github Pages provide and support. I tried to use relative URLs like `./`, `/`, and with no leading slash like in the README for this plugin, but I failed. What am I doing wrong? 🤪

@LeaVerou Lea, please, help me! 🥺

**Comment by LeaVerou** [comment]
The reason the relative link doesn't work, is that you're viewing this under a `/plugin/github-pr` URL, whereas your photos are under a `/github-pr` URL. You can use either an absolute URL, or a root-relative URL (`/github-pr/photo.png`)

**Comment by DmitrySharabin** [comment]
Got it. Thank you. I’ll send another PR soon. :)

**Pull request merged**
