### PR TITLE
Add automatic image upload when image is pasted

### PR DESCRIPTION
**Pull request by DmitrySharabin**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thank you so much! Looks good to me mostly, so I merged! Next steps:

- Mention it in the readme
- A lot of this code appears to be duplicating Mavo upload code. Is there a way to create a suitable abstraction in Mavo and call that instead of copy/pasting code?
- Please note that `document.execCommand("insertText")` does not work in Firefox. We can either just not have the feature there, or insert the text with other methods, which has the downside of disabling Undo.

**Comment by DmitrySharabin** [comment]
Thanks!
The next iteration I’ll improve it. I wasn't expecting you to merge it so fast. 😅

**Comment by DmitrySharabin** [comment]
> A lot of this code appears to be duplicating Mavo upload code. Is there a way to create a suitable abstraction in Mavo and call that instead of copy/pasting code?

What do you think of moving the `upload` function from the `Primitive` class to the `Backend` one so we can call it from everywhere? But I believe in that case we would need to change its code a bit because not in every case we need to set a property value. E.g., in Markdown, the only thing we need is to return the resulting URL.

**Comment by LeaVerou** [comment]
If all we need is to return the resulting URL, doesn't backend.upload() already do that?

**Comment by DmitrySharabin** [comment]
> If all we need is to return the resulting URL, doesn't backend.upload() already do that?

It certainly does, but unfortunately, it doesn't take into account the `mv-upload-path` and `mv-upload-url` attributes as `Primitive#upload` does. That's why I copied/pasted its code. And you're right; it would be nice if we could have some abstraction in Mavo to provide this useful feature for internal use (if needed) and plugins authors.

**Comment by LeaVerou** [comment]
Ah, I see.
Can't we juse Primitive#upload? The markdown property is still a primitive.

**Comment by DmitrySharabin** [comment]
I already tried that. The only problem is that `Primitive#upload` replaces the editor value with the returned URL, so we need to restore it manually. If you are OK with this code, I can send a PR to make code DRYer.

```js
...
// Disable editor and show placeholder while waiting for an image to upload
const placeholder = `![${env.context.mavo._("uploading")}...]()`;
document.execCommand("insertText", false, placeholder);

env.editor.disabled = true;

// Save a user's text because Primitive#upload will replace it
const oldValue = env.editor.value;

Mavo.setAttributeShy(env.context.element, "mv-upload-path", "images");
await env.context.upload(item.getAsFile(), name);
const url = env.editor.value;

// Restore the user's text after an image upload
env.editor.value = oldValue;

// Enable editor and replace the placeholder with the image element
env.editor.disabled = false;

const t = evt.target;
t.focus();
t.selectionStart = t.selectionEnd - placeholder.length;
t.setSelectionRange(t.selectionStart, t.selectionStart);

const image = `![](${url})`;
document.execCommand("insertText", false, image);
...
```

**Comment by DmitrySharabin** [comment]
And is also sets the `null` attribute because of this line:
```js
// FIXME what if there's no attribute?
this.sneak(() => this.element.setAttribute(this.attribute, tempURL));
```

**Pull request merged**
