### PR TITLE
Suggested edits to data

### PR DESCRIPTION
**Pull request by eridanired123**
Hello there! I used Mavo to suggest the following edits:
Tried to add spanish locale plugin. See it at https://gitlab.com/eridanired/spanish-locale-for-mavo/blob/master/mavo-locale-es.js
Preview my changes here: https://plugins.mavo.io/?storage=https%3A%2F%2Fraw.githubusercontent.com%2Feridanired123%2Fplugins%2Fmaster%2Fplugins.json&plugins-storage=https%3A%2F%2Fgithub.com%2Fmavoweb%2Fplugins%2Fplugins.json

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,

Thank you for creating a Spanish locale!
Unfortunately right now plugins need to be hosted on Github to be listed. That could be either a separate Github repo, or this repo. Would that be ok?

**Comment by LeaVerou** [comment]
Also, is this European Spanish or Latin American Spanish?

**Comment by eridanired123** [comment]
Yes, its OK.

Regarding the Spanish variant, I tried to be careful at avoiding localisms and regionalisms (words and grammar), so leaving it as just _Spanish_ should do.

**Comment by LeaVerou** [comment]
Since this received no response for over 6 months, I'm gonna go ahead and close it for housekeeping. Feel free to reopen if you want to work on this more!

**Pull request closed without merging**
